// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vault.dart';

/// Yeni kassa yaradır.
Future<VaultHandle> vaultCreateNew(
        {required String vaultDir, required String password}) =>
    RustLib.instance.api
        .crateApiVaultCreateNew(vaultDir: vaultDir, password: password);

/// Mövcud kassanı açır.
Future<VaultHandle> vaultUnlock(
        {required String vaultDir, required String password}) =>
    RustLib.instance.api
        .crateApiVaultUnlock(vaultDir: vaultDir, password: password);

/// Verilən qovluqda kassa mövcud görünürmü — parol tələb etmədən, sırf
/// "Aç" / "Yarat" ekranı arasında seçim üçün. Əsl təsdiq `vault_unlock`
/// çağırılanda parolla olur.
Future<bool> vaultExists({required String vaultDir}) =>
    RustLib.instance.api.crateApiVaultExists(vaultDir: vaultDir);

/// Kassanı kilidləyir (açarı yaddaşdan silir).
Future<void> vaultLock({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiVaultLock(handle: handle);

/// Kassanın kilidli olub olmadığını yoxlayır.
Future<bool> vaultIsUnlocked({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiVaultIsUnlocked(handle: handle);

/// Kassaya fayl əlavə edir.
Future<String> vaultAddFile(
        {required VaultHandle handle,
        required String sourceFilePath,
        required String originalName}) =>
    RustLib.instance.api.crateApiVaultAddFile(
        handle: handle,
        sourceFilePath: sourceFilePath,
        originalName: originalName);

/// Kassadan faylı silir.
Future<void> vaultDeleteFile(
        {required VaultHandle handle, required String obfuscatedName}) =>
    RustLib.instance.api.crateApiVaultDeleteFile(
        handle: handle, obfuscatedName: obfuscatedName);

/// Kassadakı bütün faylların siyahısını qaytarır.
Future<List<VaultFileEntry>> vaultListFiles({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiVaultListFiles(handle: handle);

/// Kassa qovluğunda olan amma hələ şifrələnməmiş (kassaya əlavə edilməmiş)
/// faylların adlarını qaytarır. Dart tərəfi bunları istifadəçiyə göstərib
/// kassaya qatmağı təklif edə bilər.
Future<List<String>> vaultListLooseFiles({required VaultHandle handle}) =>
    RustLib.instance.api.crateApiVaultListLooseFiles(handle: handle);

/// Şifrəli faylı göstərilən yola çıxarır.
Future<void> vaultExtractFileToPath(
        {required VaultHandle handle,
        required String obfuscatedName,
        required String destPath}) =>
    RustLib.instance.api.crateApiVaultExtractFileToPath(
        handle: handle, obfuscatedName: obfuscatedName, destPath: destPath);

/// Kiçik faylları bytes kimi qaytarır.
Future<Uint8List> vaultExtractFileToBytes(
        {required VaultHandle handle, required String obfuscatedName}) =>
    RustLib.instance.api.crateApiVaultExtractFileToBytes(
        handle: handle, obfuscatedName: obfuscatedName);
