// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'vault.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1516745918;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'xenonypt',
    ioDirectory: 'lib/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiVaultAddFile(
      {required VaultHandle handle,
      required String sourceFilePath,
      required String originalName});

  Future<VaultHandle> crateApiVaultCreateNew(
      {required String vaultDir, required String password});

  Future<void> crateApiVaultDeleteFile(
      {required VaultHandle handle, required String obfuscatedName});

  Future<bool> crateApiVaultExists({required String vaultDir});

  Future<Uint8List> crateApiVaultExtractFileToBytes(
      {required VaultHandle handle, required String obfuscatedName});

  Future<void> crateApiVaultExtractFileToPath(
      {required VaultHandle handle,
      required String obfuscatedName,
      required String destPath});

  Future<bool> crateApiVaultIsUnlocked({required VaultHandle handle});

  Future<List<VaultFileEntry>> crateApiVaultListFiles(
      {required VaultHandle handle});

  Future<List<String>> crateApiVaultListLooseFiles(
      {required VaultHandle handle});

  Future<void> crateApiVaultLock({required VaultHandle handle});

  Future<VaultHandle> crateApiVaultUnlock(
      {required String vaultDir, required String password});

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VaultHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VaultHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_VaultHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiVaultAddFile(
      {required VaultHandle handle,
      required String sourceFilePath,
      required String originalName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        sse_encode_String(sourceFilePath, serializer);
        sse_encode_String(originalName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultAddFileConstMeta,
      argValues: [handle, sourceFilePath, originalName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultAddFileConstMeta => const TaskConstMeta(
        debugName: "vault_add_file",
        argNames: ["handle", "sourceFilePath", "originalName"],
      );

  @override
  Future<VaultHandle> crateApiVaultCreateNew(
      {required String vaultDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultCreateNewConstMeta,
      argValues: [vaultDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultCreateNewConstMeta => const TaskConstMeta(
        debugName: "vault_create_new",
        argNames: ["vaultDir", "password"],
      );

  @override
  Future<void> crateApiVaultDeleteFile(
      {required VaultHandle handle, required String obfuscatedName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        sse_encode_String(obfuscatedName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultDeleteFileConstMeta,
      argValues: [handle, obfuscatedName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultDeleteFileConstMeta => const TaskConstMeta(
        debugName: "vault_delete_file",
        argNames: ["handle", "obfuscatedName"],
      );

  @override
  Future<bool> crateApiVaultExists({required String vaultDir}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultDir, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVaultExistsConstMeta,
      argValues: [vaultDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultExistsConstMeta => const TaskConstMeta(
        debugName: "vault_exists",
        argNames: ["vaultDir"],
      );

  @override
  Future<Uint8List> crateApiVaultExtractFileToBytes(
      {required VaultHandle handle, required String obfuscatedName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        sse_encode_String(obfuscatedName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_u_8_strict,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultExtractFileToBytesConstMeta,
      argValues: [handle, obfuscatedName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultExtractFileToBytesConstMeta =>
      const TaskConstMeta(
        debugName: "vault_extract_file_to_bytes",
        argNames: ["handle", "obfuscatedName"],
      );

  @override
  Future<void> crateApiVaultExtractFileToPath(
      {required VaultHandle handle,
      required String obfuscatedName,
      required String destPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        sse_encode_String(obfuscatedName, serializer);
        sse_encode_String(destPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultExtractFileToPathConstMeta,
      argValues: [handle, obfuscatedName, destPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultExtractFileToPathConstMeta =>
      const TaskConstMeta(
        debugName: "vault_extract_file_to_path",
        argNames: ["handle", "obfuscatedName", "destPath"],
      );

  @override
  Future<bool> crateApiVaultIsUnlocked({required VaultHandle handle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVaultIsUnlockedConstMeta,
      argValues: [handle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultIsUnlockedConstMeta => const TaskConstMeta(
        debugName: "vault_is_unlocked",
        argNames: ["handle"],
      );

  @override
  Future<List<VaultFileEntry>> crateApiVaultListFiles(
      {required VaultHandle handle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_vault_file_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultListFilesConstMeta,
      argValues: [handle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultListFilesConstMeta => const TaskConstMeta(
        debugName: "vault_list_files",
        argNames: ["handle"],
      );

  @override
  Future<List<String>> crateApiVaultListLooseFiles(
      {required VaultHandle handle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultListLooseFilesConstMeta,
      argValues: [handle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultListLooseFilesConstMeta =>
      const TaskConstMeta(
        debugName: "vault_list_loose_files",
        argNames: ["handle"],
      );

  @override
  Future<void> crateApiVaultLock({required VaultHandle handle}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
            handle, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiVaultLockConstMeta,
      argValues: [handle],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultLockConstMeta => const TaskConstMeta(
        debugName: "vault_lock",
        argNames: ["handle"],
      );

  @override
  Future<VaultHandle> crateApiVaultUnlock(
      {required String vaultDir, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(vaultDir, serializer);
        sse_encode_String(password, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiVaultUnlockConstMeta,
      argValues: [vaultDir, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiVaultUnlockConstMeta => const TaskConstMeta(
        debugName: "vault_unlock",
        argNames: ["vaultDir", "password"],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_VaultHandle => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_VaultHandle => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle;

  @protected
  VaultHandle
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  VaultHandle
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return VaultHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<VaultFileEntry> dco_decode_list_vault_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_vault_file_entry).toList();
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VaultFileEntry dco_decode_vault_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VaultFileEntry(
      obfuscatedName: dco_decode_String(arr[0]),
      originalName: dco_decode_String(arr[1]),
    );
  }

  @protected
  VaultHandle
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  VaultHandle
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return VaultHandleImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<VaultFileEntry> sse_decode_list_vault_file_entry(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VaultFileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_vault_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VaultFileEntry sse_decode_vault_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_obfuscatedName = sse_decode_String(deserializer);
    var var_originalName = sse_decode_String(deserializer);
    return VaultFileEntry(
        obfuscatedName: var_obfuscatedName, originalName: var_originalName);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          VaultHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VaultHandleImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerVaultHandle(
          VaultHandle self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as VaultHandleImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_vault_file_entry(
      List<VaultFileEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_vault_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_vault_file_entry(
      VaultFileEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.obfuscatedName, serializer);
    sse_encode_String(self.originalName, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class VaultHandleImpl extends RustOpaque implements VaultHandle {
  // Not to be used by end users
  VaultHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  VaultHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_VaultHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_VaultHandlePtr,
  );
}
