// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultFileStream>>
abstract class VaultFileStream implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultHandle>>
abstract class VaultHandle implements RustOpaqueInterface {}

/// Növbə ilə fayl əlavə etmək üçün giriş parametri.
class VaultAddFileInput {
  final String sourceFilePath;
  final String originalName;

  const VaultAddFileInput({
    required this.sourceFilePath,
    required this.originalName,
  });

  @override
  int get hashCode => sourceFilePath.hashCode ^ originalName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultAddFileInput &&
          runtimeType == other.runtimeType &&
          sourceFilePath == other.sourceFilePath &&
          originalName == other.originalName;
}

/// Növbə ilə fayl çıxarmaq üçün giriş parametri.
class VaultExtractFileInput {
  final String obfuscatedName;
  final String destPath;

  const VaultExtractFileInput({
    required this.obfuscatedName,
    required this.destPath,
  });

  @override
  int get hashCode => obfuscatedName.hashCode ^ destPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultExtractFileInput &&
          runtimeType == other.runtimeType &&
          obfuscatedName == other.obfuscatedName &&
          destPath == other.destPath;
}

/// Kassadakı bir faylın metadata qeydi. FRB bunu Dart-da adi bir
/// klas (freezed olmayan sadə data class) kimi generasiya edəcək.
class VaultFileEntry {
  /// Diskdə saxlanılan təsadüfi (obfuscated) fayl adı.
  final String obfuscatedName;

  /// İstifadəçiyə göstərilən əsl fayl adı.
  final String originalName;

  const VaultFileEntry({
    required this.obfuscatedName,
    required this.originalName,
  });

  @override
  int get hashCode => obfuscatedName.hashCode ^ originalName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultFileEntry &&
          runtimeType == other.runtimeType &&
          obfuscatedName == other.obfuscatedName &&
          originalName == other.originalName;
}
