// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VaultHandle>>
abstract class VaultHandle implements RustOpaqueInterface {}

/// Kassadakı bir faylın metadata qeydi. FRB bunu Dart-da adi bir
/// klas (freezed olmayan sadə data class) kimi generasiya edəcək.
class VaultFileEntry {
  /// Diskdə saxlanılan təsadüfi (obfuscated) fayl adı.
  final String obfuscatedName;

  /// İstifadəçiyə göstərilən əsl fayl adı.
  final String originalName;

  const VaultFileEntry({
    required this.obfuscatedName,
    required this.originalName,
  });

  @override
  int get hashCode => obfuscatedName.hashCode ^ originalName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultFileEntry &&
          runtimeType == other.runtimeType &&
          obfuscatedName == other.obfuscatedName &&
          originalName == other.originalName;
}
